### ISSUE TITLE
How to convert sam json to tsv data formats?

### ISSUE THREAD

**Issue by shipengai** [UX-Decoder/Semantic-SAM#17]
How to convert sam json to tsv data formats?
May the "data prepare" be more detailed

**Comment by shipengai** [comment]
python version need >= 3.8?

**Comment by FengLi-ust** [comment]
Yes. We have provided more detailed data preparation, please refer to https://github.com/UX-Decoder/Semantic-SAM/blob/main/DATASET.md

**Comment by dawang-11** [comment]
作者、我想请教一下，我转为tsv data formats后，生成两个文件，index_output.txt和tsv_output.tsv,但我运行后面的训练代码，涉及到将其分为100份，这啥意思哦
