### ISSUE TITLE
AssertionError: Dataset 'sam_train' is empty!

### ISSUE THREAD

**Issue by shipengai** [UX-Decoder/Semantic-SAM#19]
How  to register sam？

**Comment by shipengai** [comment]
subfolder = os.path.join(dirname, 'sa_%06d' % id, 'image_list.da')
what is image_list.da?

**Comment by shipengai** [comment]
how to generate "image_list.da"?

**Comment by FengLi-ust** [comment]
We have provided more detailed data preparation, please refer to https://github.com/UX-Decoder/Semantic-SAM/blob/main/DATASET.md

**Comment by dawang-11** [comment]
hello、have you solved this problem?
