### ISSUE TITLE
sam 社群 群聊

### ISSUE THREAD

**Issue by willshion** [UX-Decoder/Semantic-SAM#20]
![bdb8efb9ffe9327bbafb785c1eb66e7](https://github.com/UX-Decoder/Semantic-SAM/assets/13349979/adb5cccf-68e9-46e9-89c7-3c7969c258c6)

**Comment by willshion** [comment]
微信我拉 willshion88

**Comment by woshitiancai321** [comment]
拉我下  handongshen0129
