### ISSUE TITLE
Running inference on a single image?

### ISSUE THREAD

**Issue by kenhuangsy** [UX-Decoder/Semantic-SAM#29]
Is there a way to run inference on a single image where a coordinate is inputted and the model will segment the object at that coordinate? Sort of similar to how SAM allows you to segment with clicking?

**Comment by FengLi-ust** [comment]
Hi, we have released a simple getting started code for you to inference more conveniently.

**Comment by kenhuangsy** [comment]
Thank you @FengLi-ust  :+1:
