### ISSUE TITLE
predict iou loss is different from sam?

### ISSUE THREAD

**Issue by shipengai** [UX-Decoder/Semantic-SAM#30]
[https://github.com/UX-Decoder/Semantic-SAM/blob/main/semantic_sam/modules/criterion_interactive_many_to_one.py#L380C9-L380C35](url)
`target_iou = 1 - dice_loss `
after this code ,the target iou is dice not iou.

**Comment by FengLi-ust** [comment]
Yes, we use dice as the iou loss.
