### ISSUE TITLE
Inquiry about the 'prompt_switch' function in the code

### ISSUE THREAD

**Issue by 1angmul2** [UX-Decoder/Semantic-SAM#36]
I have been going through the code in the repository, and I came across the 'prompt_switch' function. I am trying to understand how this function determines the switching between different levels of granularity. It seems that there is no specific handling for different granularity in the training code. Could you please shed some light on how it works and how it handles the switching between various levels of granularity?
Thank you in advance for your assistance!

**Comment by FengLi-ust** [comment]
Thanks for this interesting problem. Actually, this granularity-aware property automatically emerges in training our many2many objectives.

**Comment by 1angmul2** [comment]
Thank you for your response. I noticed that the SAM reproduction uses the 'many2one' strategy, as there is no corresponding inference code available. I was wondering whether the same handling method is required for granularity during inference as well.
