### ISSUE TITLE
训练的时候加载的是什么模型呀？

### ISSUE THREAD

**Issue by KeyKy** [UX-Decoder/Semantic-SAM#40]
```
python train_net.py --resume --num-gpus $n  --config-file configs/semantic_sam_only_sa-1b_swinL.yaml COCO.TEST.BATCH_SIZE_TOTAL=$n  SAM.TEST.BATCH_SIZE_TOTAL=$n  SAM.TRAIN.BATCH_SIZE_TOTAL=$n MODEL.WEIGHTS=/path/to/weights
```
MODEL.WEIGHTS 可以不传吗？

现在的训练代码可以train from scratch的 复现1-IoU@COCO(Max|Oracle)54.5|73.8的指标吗？我看代码好像只用了0-100的sa1b的数据，是不是没用全？

**Comment by FengLi-ust** [comment]
是的，训练的时候是from scratch训练的，加载的是swinl的imagenet上的backbone，可以去掉这个参数。
参照我们的文件格式，我们吧sa-1b的数据转成了100份tsv数据，所以是全部数据。

**Comment by KeyKy** [comment]
@FengLi-ust 我把sa-1b 转成了1000分tsv数据，只用了0-100，就能到miou@iter1': 0.5278'

**Comment by FengLi-ust** [comment]
是的，这部分结果我们在文章的ablation里面也有呈现。

**Comment by KeyKy** [comment]
我10%的数据训出来的模型主观评测，还是会弱于开放的swinT
![all_results_sort_by_iou](https://github.com/UX-Decoder/Semantic-SAM/assets/2967075/8fa8dbc4-03b0-46fb-a642-8c404343046e)
