### ISSUE TITLE
Issue when running Semantic-SAM with box input

### ISSUE THREAD

**Issue by KolinGuo** [UX-Decoder/Semantic-SAM#45]
Hi, thank you for releasing the code and checkpoint!

I was trying to run Semantic-SAM with bounding box input (instead of point click) but the result on the dog example seems to be wrong (see the attacked images).

Based on the paper, the click and box prompts should in the same `(x, y, w, h)` format with point clicks having a small `w` and `h`, which is what I did below. Are there anything I'm missing when running Semantic-SAM with box input or is the code for that not released yet?

Thank you in advance!

```
import torch
from semantic_sam import prepare_image, plot_multi_results, build_semantic_sam, SemanticSAMPredictor
def box_xyxy_to_cxcywh(x):
    x0, y0, x1, y1 = x.unbind(-1)
    b = [(x0 + x1) / 2, (y0 + y1) / 2,
         (x1 - x0), (y1 - y0)]
    return torch.stack(b, dim=-1)

# Resize image s.t. smaller edge is 640
# original_image is np.ndarray HWC, input_image is torch.Tensor CHW
original_image, input_image = prepare_image(image_pth=f'{REPO_PATH}/examples/dog.jpg')  # change the image path to your image
height, width = original_image.shape[:2]
mask_generator = SemanticSAMPredictor(build_semantic_sam(
    model_type='L',
    ckpt=f'{REPO_PATH}/models/swinl_only_sam_many2many.pth')) # model_type: 'L' / 'T', depends on your checkpint
bbox_xyxy = [350.0, 100, 650, 600]
iou_sort_masks, area_sort_masks = mask_generator.predict_masks(
    original_image, input_image,
    point=box_xyxy_to_cxcywh(torch.tensor([bbox_xyxy])) / torch.tensor([width, height, width, height]),  # [xywh]
) # input point [[w, h]] relative location, i.e, [[0.5, 0.5]] is the center of the image
plot_multi_results(iou_sort_masks, area_sort_masks, original_image, save_path='./vis/')  # results and original images will be saved at save_path

import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(8, 8))
ax.imshow(original_image)
ax.set_axis_off()
x_min, y_min, x_max, y_max = bbox_xyxy
ax.plot([x_min, x_max, x_max, x_min, x_min],
        [y_min, y_min, y_max, y_max, y_min], "r")
```
![image](https://github.com/UX-Decoder/Semantic-SAM/assets/26679459/95aa11c8-b354-4ccc-b310-d659c80fd9cf)
![image](https://github.com/UX-Decoder/Semantic-SAM/assets/26679459/c6622f12-66a6-4f31-9758-6777bd5e157e)

**Comment by FengLi-ust** [comment]
The released checkpoint is only trained on point input. As box input does not have ambiguity, this is not the focus of our model. Our code also supports box training. If you want box input, finetune our model for only a few thousand iterations training is enough to achieve good box input segmentation results.

**Comment by KolinGuo** [comment]
I see, thank you for the reply!

**Comment by Damehou** [comment]
> 

hello,Have you used a box as input for finetuning?I have some questions, i modify the config like this
<img width="241" alt="截屏2023-08-23 16 34 51" src="https://github.com/UX-Decoder/Semantic-SAM/assets/35283063/e74539f5-9ea2-430f-88b9-9c00d0985d14">
