### ISSUE TITLE
segmentation result imperfect

### ISSUE THREAD

**Issue by JonathanLi19** [UX-Decoder/Semantic-SAM#47]
Hi, great work! I want to ask why this mask prediction using 'All Prompt' isn't perfect. (There should be a mask in my circle, but there isn't.) 
![result](https://github.com/UX-Decoder/Semantic-SAM/assets/73473823/a90d4e4b-e446-4ad5-adee-5293065e4eed)

**Comment by FengLi-ust** [comment]
Hi, thanks for your feedback. With the same picture, I also try the demo **multiple times** and the results always include the 'imperfect' mask.
<img width="397" alt="image" src="https://github.com/UX-Decoder/Semantic-SAM/assets/34880758/3ffa67e7-b436-499b-9522-ab06b8a57028">
I think the result has some randomness (SAM also has), but most of the time the output masks are reasonable. Could you try it again?

**Comment by FengLi-ust** [comment]
Hi, I think you use a different resolution during inference. We use `640` for the short edge, while you seem to use `800` for the short edge. As our auto-generation uses a fixed number of points (32x32 points) for an image, if you use a larger image, you need to use for points to cover the whole image.

**Comment by JonathanLi19** [comment]
> 

Thank you! The problem has been solved.
