### ISSUE TITLE
seems the demo link is dead?

### ISSUE THREAD

**Issue by SilenceGoo** [UX-Decoder/Semantic-SAM#54]
not 100% sure but seems the demo stopped working since days ago? Could anyone visit and try it now? Thanks.

**Comment by BigBigMonsterProgramer** [comment]
I get the same problem.

**Comment by SilenceGoo** [comment]
Demo link is awake now but still cant see result after click run button, even waiting mins.

**Comment by FengLi-ust** [comment]
Thanks for the comment. We have updated the demo and it is now working.
