### ISSUE TITLE
Does mask auto generation have semantic labels? 

### ISSUE THREAD

**Issue by XinyingZheng** [UX-Decoder/Semantic-SAM#73]
你好，我见mask auto generation方法只输出了不同细粒度的mask，没有mask对应的语义类别标签输出是么

**Comment by FengLi-ust** [comment]
Yes, semantically trained model is not released yet.

**Comment by Aki-Tomoya** [comment]
> Yes, semantically trained model is not released yet.

Can you tell me when the pre-trained model with semantic mask will be released? Very much looking forward to your work!
